export const PROFILE = {
  name: "Sandeep Kothapalli",
  title: "Technical Lead | Solution Architect | Cloud & Distributed Systems (AI-Enabled Platforms)",
  shortTitle: "Technical Lead",
  tagline: "Solution Architect · Cloud & Distributed Systems · AI-Enabled Platforms",
  location: "Bangalore, India",
  locationFull: "Bangalore, India (Open to US / EU / Remote)",
  email: "Sandeep.kothapalli1@hotmail.com",
  phone: "+91-8019145771",
  url: "https://kothapallisandeep.com",
  currentRole: "Technical Lead, Progience Technologies",
  currentRoleDetail: "Solution Architect · Serverless & Cloud-Native · AI-Enabled Platforms",
  summary: [
    "Senior Technical Lead and Solution Architect with 13+ years of experience designing and delivering enterprise-scale, serverless architecture and cloud-native platforms. Strong expertise in .NET, TypeScript, AWS, Azure, microservices, Dapr, Kubernetes, distributed systems, system design, Python, and FastAPI, with a proven track record of leading teams, defining technical roadmaps, and modernizing legacy systems.",
    "Over the past year, expanded expertise into AI-enabled systems, contributing to the design and integration of LLM-based features such as RAG pipelines and agent-driven workflows within existing cloud and microservices architectures. Known for balancing scalability, reliability, security, and performance while aligning technology with business outcomes.",
  ],
  progienceTechnologies:
    ".NET Core, C#, TypeScript, Python, FastAPI, AWS (Serverless/Lambda), Cloudflare Workers, Microsoft Azure, SQL, Entity Framework, Design Patterns, Azure AI Foundry, Azure Functions, PostgreSQL, Azure AD, Azure Blob Storage, Azure AI",
  specializations: [
    "Serverless & cloud-native architecture (.NET, Azure, AWS, Kubernetes, Dapr)",
    "AI-enabled platforms — RAG pipelines, agent workflows, and LLM integration",
    "Enterprise microservices, event-driven systems, and distributed system design",
    "Legacy modernization — monolith to microservices with zero-downtime strategies",
    "Full-stack delivery — React, Next.js, TypeScript, Python, FastAPI",
  ],
  linkedin: "https://www.linkedin.com/in/kothapallisandeep/",
  github: "https://github.com/websabre",
  twitter: "https://x.com/sandeepattech",
} as const;

export const SKILLS = {
  "Architecture & Design": [
    "Domain-Driven Design (DDD)",
    "Clean Architecture",
    "Event-Driven Architecture",
    "System Design & Distributed Systems",
    "Microservices Architecture & Dapr Actor Model",
    "Performance Optimization & Reliability Engineering",
    "High Availability, Scalability & Resilience",
  ],
  "AI & LLM": [
    "Agent-based Workflows & Tool Invocation",
    "AI Performance Considerations (Latency, Cost, Accuracy)",
    "Secure AI Feature Integrations in Cloud Systems",
    "RAG Fundamentals",
    "Vector Search & Embeddings",
    "LLM Integration in Enterprise Applications",
    "Prompt Engineering for Production Workflows",
    "Structured Prompting & Output Parsing",
    "Context Assembly & Ranking for LLM Inputs",
    "Token Usage Optimization & Prompt Compression",
    "Vector Indexing & Similarity Search",
    "Hybrid Retrieval (Vector + Keyword Search)",
    "Applied Vector Stores (Cloud-Managed or Open-Source)",
  ],
  "Programming & Frameworks": ["C#", ".NET", "ASP.NET Core", "JavaScript", "TypeScript", "Python", "FastAPI"],
  "Frontend & Mobile": ["React", "React Native", "Next.js", "JavaScript", "TypeScript"],
  "Cloud & DevOps": [
    "Microsoft Azure",
    "Amazon Web Services (AWS)",
    "Serverless (Lambda)",
    "Cloudflare Workers",
    "Kubernetes",
    "CI/CD",
    "DevOps & Observability",
    "Git",
    "Azure DevOps",
    "Azure Pipelines",
    "Terraform",
    "Automated Testing",
  ],
  "Databases": ["SQL Server", "Azure Cosmos DB", "Azure PostgreSQL Flexible Server", "PostgreSQL", "NoSQL"],
  "APIs & Services": ["API-First Design (REST, gRPC)", "Dapr", "Actor Model", "Microservices", "Azure Functions", "Azure AI Foundry"],
  "Tools & Practices": [
    "Sprint Planning & Estimation",
    "Code Reviews & Engineering Best Practices",
    "Supply Chain Security",
    "Azure AD",
    "Azure Blob Storage",
  ],
} as const;
